bcm963xx_CAC002-31.30L.74_consumer_release   Commit of Actiontec C1000A firmware CAC002 31.30L.74 pulled from   http://opensource.actiontec.com/c1000x.html,   bcm963xx_CAC002-31.30L.74_consumer_release_C1000A.tar.gz   dated 2014/11/16. bcm963xx_router and toolchains installs   to /opt.

diff --git a/bcm963xx_router/userspace/gpl/apps/busybox/testsuite/runtest b/bcm963xx_router/userspace/gpl/apps/busybox/testsuite/runtest
--- a/bcm963xx_router/userspace/gpl/apps/busybox/testsuite/runtest
+++ b/bcm963xx_router/userspace/gpl/apps/busybox/testsuite/runtest
@@ -1,102 +1,163 @@
 #!/bin/sh
+# Usage:
+# runtest [applet1] [applet2...]
 
-[ -n "$srcdir" ] || srcdir=$(pwd)
-[ -n "$bindir" ] || bindir=$(dirname $(pwd))
-PATH=$bindir:$PATH
+. ./testing.sh
 
-run_applet_testcase ()
+# Run one old-style test.
+# Tests are stored in applet/testcase shell scripts.
+# They are run using "sh -x -e applet/testcase".
+# Option -e will make testcase stop on the first failed command.
+run_applet_testcase()
 {
-	local applet=$1
-	local testcase=$2
+	local applet="$1"
+	local testcase="$2"
 
 	local status=0
-	local RES=
+	local uc_applet=$(echo "$applet" | tr a-z A-Z)
+	local testname="$testcase"
 
-	local uc_applet=$(echo $applet | tr a-z A-Z)
-	local testname=$(basename $testcase)
-
-	if grep -q "^# CONFIG_${uc_applet} is not set$" $bindir/.config; then
-		echo UNTESTED: $testname
+	testname="${testname##*/}" # take basename
+	if grep "^# CONFIG_$uc_applet is not set$" "$bindir/.config" >/dev/null; then
+		echo "UNTESTED: $testname"
 		return 0
 	fi
 
-	if grep -q "^# FEATURE: " $testcase; then
-		local feature=`sed -ne 's/^# FEATURE: //p' $testcase`
+	if grep "^# FEATURE: " "$testcase" >/dev/null; then
+		local feature=$(sed -ne 's/^# FEATURE: //p' "$testcase")
 
-		if grep -q "^# ${feature} is not set$" $bindir/.config; then
-			echo UNTESTED: $testname
-			return 0
+		for f in $feature; do
+			if grep "^# $f is not set$" "$bindir/.config" >/dev/null; then
+				echo "UNTESTED: $testname"
+				return 0
+			fi
+		done
+	fi
+
+	rm -rf ".tmpdir.$applet"
+	mkdir -p ".tmpdir.$applet"
+	cd ".tmpdir.$applet" || return 1
+
+#	echo "Running testcase $testcase"
+	d="$tsdir" \
+		sh -x -e "$testcase" >"$testname.stdout.txt" 2>&1 || status=$?
+	if [ $status -ne 0 ]; then
+		echo "FAIL: $testname"
+		if [ x"$VERBOSE" != x ]; then
+			cat "$testname.stdout.txt"
 		fi
-	fi
-
-	rm -rf tmp
-	mkdir -p tmp
-	pushd tmp >/dev/null
-
-	d=$srcdir sh -x -e $testcase >.logfile.txt 2>&1
-
-	if [ $? != 0 ] ; then
-		echo FAIL: $testname
-		if [ "$verbose" = 1 ]; then
-			cat .logfile.txt
-			#exit 1;
-		fi;
-		status=$?
 	else
-		echo PASS: $testname
-		rm -f .logfile.txt
-		status=$?
+		echo "PASS: $testname"
 	fi
 
-	popd >/dev/null
-	rm -rf tmp
+	cd ..
+	rm -rf ".tmpdir.$applet"
 
 	return $status
 }
 
-run_applet_tests ()
+# Run all old-style tests for given applet
+run_oldstyle_applet_tests()
 {
-	local applet=$1
-
+	local applet="$1"
 	local status=0
 
-	for testcase in $srcdir/$applet/*; do
-		if [ "$testcase" = "$srcdir/$applet/CVS" ]; then
-			continue
-		fi
-
-		if run_applet_testcase $applet $testcase; then
-			:
-		else
-			status=1
-		fi
+	for testcase in "$tsdir/$applet"/*; do
+		# switch on basename of $testcase
+		case "${testcase##*/}" in
+			.*)     continue ;;    # .svn, .git etc
+			*~)     continue ;;    # backup files
+			"CVS")  continue ;;
+			\#*)    continue ;;    # CVS merge residues
+			*.mine) continue ;;    # svn-produced junk
+			*.r[0-9]*) continue ;; # svn-produced junk
+		esac
+		run_applet_testcase "$applet" "$testcase" || status=1
 	done
-
 	return $status
 }
 
 
-status=0
+
+lcwd=$(pwd)
+[ x"$tsdir" != x"" ] || tsdir="$lcwd"
+[ x"$bindir" != x"" ] || bindir="${lcwd%/*}" # one directory up from $lcwd
+PATH="$bindir:$PATH"
+export bindir   # some tests need to look at $bindir/.config
+
+if [ x"$VERBOSE" = x ]; then
+	export VERBOSE=
+fi
 
 if [ x"$1" = x"-v" ]; then
-	verbose=1
+	export VERBOSE=1
 	shift
 fi
 
+implemented=$(
+	printf "busybox " # always implemented
+	"$bindir/busybox" 2>&1 |
+	while read line; do
+		if [ x"$line" = x"Currently defined functions:" ]; then
+			xargs | sed 's/,//g'
+			break
+		fi
+	done
+	)
+
+applets="$implemented"
 if [ $# -ne 0 ]; then
 	applets="$@"
-else
-	applets=$(ls $srcdir)
 fi
 
+# Populate a directory with links to all busybox applets
+
+LINKSDIR="$bindir/runtest-tempdir-links"
+
+# Comment this line out if you have put a different binary in $LINKSDIR
+# (say, a "standard" tool's binary) in order to run tests against it:
+rm -rf "$LINKSDIR" 2>/dev/null
+
+mkdir "$LINKSDIR" 2>/dev/null
+for i in $implemented; do
+	# Note: if $LINKSDIR/applet exists, we do not overwrite it.
+	# Useful if one wants to run tests against a standard utility,
+	# not an applet.
+	ln -s "$bindir/busybox" "$LINKSDIR/$i" 2>/dev/null
+done
+
+# Set up option flags so tests can be selective.
+export OPTIONFLAGS=:$(
+	sed -nr 's/^CONFIG_//p' "$bindir/.config" |
+	sed 's/=.*//' | xargs | sed 's/ /:/g'
+	):
+
+status=0
 for applet in $applets; do
-	if [ "$applet" != CVS -a -d "$srcdir/$applet" ]; then
-		if run_applet_tests $applet; then
-			:
-		else
-			status=1
+	# Any old-style tests for this applet?
+	if [ -d "$tsdir/$applet" ]; then
+		run_oldstyle_applet_tests "$applet" || status=1
+	fi
+
+	# Is this a new-style test?
+	if [ -f "$applet.tests" ]; then
+		if [ ! -e "$LINKSDIR/$applet" ]; then
+			# (avoiding bash'ism "${applet:0:4}")
+			if ! echo "$applet" | grep "^all_" >/dev/null; then
+				echo "SKIPPED: $applet (not built)"
+				continue
+			fi
 		fi
+#		echo "Running test $tsdir/$applet.tests"
+		PATH="$LINKSDIR:$tsdir:$bindir:$PATH" \
+			"$tsdir/$applet.tests" || status=1
 	fi
 done
 
+# Leaving the dir makes it somewhat easier to run failed test by hand
+#rm -rf "$LINKSDIR"
+
+if [ $status -ne 0 ] && [ x"$VERBOSE" = x ]; then
+	echo "Failures detected, running with -v (verbose) will give more info"
+fi
 exit $status
